poseidon/terraform-provider-ct

Makefile
main.go

Fuze has been renames, and so has this provider. Just finishing the rename here.

Rename Fuze to CT

---

ct/datasource_ct_config.go
ct/datasource_ct_config_test.go

* Add a platform field to the ct_config resource to enable platform-specific templating. Details on platform-specific templating can be found in https://github.com/coreos/container-linux-config-transpiler/blob/master/config/templating/templating.go#L27
* Platform defaults to "", which performs no platform-specific templating (i.e. bare-metal or other platforms)
```
data "ct_config" "controller" {
pretty_print = false
provider     = "gce"
content      = "${file("controller.yaml")}"
}
resource "google_compute_instance_template" "controller" {
machine_type = "${var.machine_type}"
metadata {
user-data = "${data.ct_config.controller.rendered}"
}
...
```
Fixes https://github.com/coreos/bugs/issues/2049
cc @bloo

ct: Add platform field to config resource type

---

.gitignore
.travis.yml
CHANGES.md
Makefile
README.md
scripts/git-version

* Structure README and requirements following upstream Terraform providers
* Add a release target which builds statically linked plugins and tarballs
*Note:* This will be the last release with the name "terraform-provider-ct". See #7 and #12

*: Prepare for v0.2.0 release

---

README.md

* Let's spruce these docs up before cutting the next release which will generate Ignition v2.1.0.
* Start communicating in terms of providing users the ability to use Container Linux Configs, rather than in terms of `ct` or "transpiling" which is more internal
* Users have no way to know about platforms. Document available platforms and make it clear they're optional.

README: Improve introduction, usage, and links

---

ct/datasource_ct_config.go
ct/datasource_ct_config_test.go
glide.lock
vendor/github.com/coreos/ignition/config/validate/astjson/node.go
vendor/go4.org/LICENSE
vendor/go4.org/errorutil/highlight.go

Allow users to supply a list of Container Linux Configs that should be appended. This means base
configs can be additively extended with custom snippets of Container Linux configs. This is a long-awaited feature to unlock end-user customizations.
I'm putting this up for comment, but still working on validating the usage in real-world scenarios.
```
data "ct_config" "worker" {
content      = "${file("base.yaml")}"
platform     = "ec2"
pretty_print = false
snippets = [
"${file("units.yaml")}",
"${file("storage.yaml")}",
]
}
resource "aws_instance" "worker" {
user_data = "${data.ct_config.worker.rendered}"
}
```
rel: https://github.com/coreos/matchbox/issues/622

Add ability to append Container Linux snippets

---

.travis.yml
README.md

Test against Go v1.9, v1.10, and v1.11

Update .travis for Go v1.11, remove v1.8

---

README.md

* Refresh the requirements, install, and usage documentation
* Use Terraform's 3rd-party plugin directory to provide a mechinism
for migrating infrastructure between plugin versions
* https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
Note: List Terraform v0.11 as a requirement. While nothing has been done to
break functionality with old Terraform versions, they're quite old. Going
forward, v0.11+ will be assumed

Improve instructions to use the 3rd-party plugin directory

---

CHANGES.md
Makefile
README.md
go.mod
main.go

* Change the module name to reflect the new repo location
* Update README and CHANGES with the new repo location

Rename module to github.com/poseidon/terraform-provider-ct

---

.travis.yml

* Test the latest 3 versions of Go for consistency across projects

Add .travis.yml test coverage for Go v1.12.x

---

ct/datasource_ct_config.go
ct/datasource_ct_config_test.go

If snippet in Terraform code is optional, for example when ternary
operator is used, then provider is not able to handle at the moment and
crashes, trying to cast 'nil' interface into string.
This commit changes the logic to prevent that and makes that only non
'nil' snippets will be used.
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

Gracefully handle empty snippets

---

CHANGES.md

* Add release note for [#61](https://github.com/poseidon/terraform-provider-ct/pull/61)
* Likely the last release with Container Linux Config Ignition v2.2 spec, https://github.com/poseidon/terraform-provider-ct/pull/60 uses v2.3 spec

Update release notes for v0.5.1

---

README.md
docs/index.md

* Show usage of ct provider from the Terraform Registry
* Rename 3rd-party plugin install to legacy install (for Terraform v0.12)

Favor Terraform v0.13 usage in README and index

---

ct/datasource_ct_config.go
ct/datasource_ct_config_test.go

When `pretty_print = false` is used along with FCC 1.1 configuration _and_ snippets, the result is an empty (default) Ignition document. Adapting a case from the tests:
```tf
terraform {
required_version = ">= 0.13"
required_providers {
ct = {
source  = "poseidon/ct"
version = "~> 0.7.0"
}
}
}
data "ct_config" "fedora-coreos-snippets" {
pretty_print = false
strict = true
content = <<EOT
---
variant: fcos
version: 1.1.0
passwd:
users:
- name: core
ssh_authorized_keys:
- key
EOT
snippets = [
<<EOT
---
variant: fcos
version: 1.1.0
systemd:
units:
- name: docker.service
enabled: true
EOT
]
}
output "ignition" {
value = data.ct_config.fedora-coreos-snippets.rendered
}
```
The result is:
```
$ terraform apply -auto-approve
data.ct_config.fedora-coreos-snippets: Refreshing state... …
```

Fix empty "rendered" with FCC 1.1 and snippets

---

README.md
ct/datasource_ct_config_test.go

* Fedora CoreOS Config v1.3.0 transpiles to Ignition v3.2.0, just like FCC v1.2.0 (notice)

Add Fedora CoreOS Config v1.3.0 spec coverage

---

examples/content/fcc-snippet.yaml
examples/content/fcc.yaml
examples/versions.tf

* Allow using Terraform v0.13 or v0.14 in example
* Show using the Fedora CoreOS Config version v1.3.0.
Note that FCC v1.3.0 (like v1.2.0) renders to Ignition 3.2.0 (no change)

Update examples from ct v0.7.1 to v0.8.0

---

Makefile

* Originally, Terraform Providers were packaged in tarball archives like any typical Go binary release. In Terraform
today, provider plugins are fetched from the Terraform Registry, which uses a zip file format for ingestion
* Consolidate to just using the zip format for releases, it contains the same binaries compiled for OSes/archs
Rel: https://registry.terraform.io/providers/poseidon/ct/latest

Remove tarball release archive format

---

ct/datasource_ct_config.go
go.mod
go.sum

* The upstream `github.com/coreos/fcct` module was renamed to `github.com/coreos/butane`
* Update butane from v0.10.0 to v0.11.0
Rel: https://github.com/coreos/butane/releases/tag/v0.11.0

Rename github.com/coreos/fcct to github.com/coreos/butane

---

go.mod
go.sum

* Dependabot will not auto-update if we're not on a release

Update ignition/v2 to a release v2.10.1

---

README.md
ct/datasource_ct_config.go
ct/datasource_ct_config_test.go

* Butane Config (formerly Fedora CoreOS Config) v1.4.0 transpiles to Ignition v3.3.0

Add Butane Config v1.4.0 support

---

.github/workflows/test.yaml
docs/index.md

* Update Github Actions `setup-go` and `checkout`
* Change `go get <tool>` to `go install <tool>`
* Remove Go v1.16

Add Go v1.18 to test matrix

---

.github/workflows/test.yaml
CHANGES.md
README.md
ct/datasource_ct_config_flatcar_test.go
docs/index.md
go.mod

* Add tests for Butane Config flatcar variant
* Update README and docs for v0.11.0 release
* Update minimum Go version to v1.17
* Deprecate Container Linux Config, these can be written as Butane Configs with the new flatcar variant
```tf
variant: flatcar
version: 1.0.0
passwd:
users:
- name: core
ssh_authorized_keys:
- ssh-key foo
```

Add Butane Config flatcar variant

---

docs/data-sources/ct_config.md

The transpilation is now done for Butane only.
Also fix a broken link.

docs: Remove last references to CLC

---

CHANGES.md
README.md
docs/index.md
examples/versions.tf

* Release v0.12.0 converts Butane Configs to Ignition spec v3.3.0 (via forward compatibility)

Release poseidon/ct v0.12.0

---

CHANGES.md
Makefile
README.md
ct/datasource_ct_config.go
ct/datasource_ct_config_flatcar_test.go
ct/datasource_ct_config_test.go

* Upstream Ignition has stabalized the v3.4.0 spec and can parse and merge earlier versions to v3.4.0 (Ignition forward compatibility)
* Convert fcos variant Butane Configs to Ignition v3.4.0 spec
* Convert flatcar variant Butane Configs to Ignition v3.4.0 spec

Update the target stable Ignition spec version to v3.4.0

---

CHANGES.md
README.md
examples/versions.tf
internal/data_config.go

* Remove the `platform` field, which was deprecated in v0.12.0

Remove deprecated platform field from ct_config

---

.github/release.yaml
Makefile

* Configure the release target to copy the release binary to the appropriate local location to test it without publishing

Improve Makefile for local release testing

---

internal/data_config.go

Without the report, if there is an error during translation, there is no explanation of where and why the error occurred

Add butane translate report to error message
